### PR TITLE
Bug Fix for Home page error 

### PR DESCRIPTION
**Pull request by dulranga**
testing Layout without hooks and without <BrowserOnly>

### CODE REVIEW

**Comment by ErKeLost** [comment]
this is new code
```tsx
const MainContent = () => (
  <main className="mb-20 my-10 max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8max-w-6xl">
    <AnimatedGradientStarWithGithub />
    <HomepageHeader />
    <BentoGridCard />
  </main>
);

const AuroraBackContent = () => (
  <AuroraBackground>
    <MainContent />
  </AuroraBackground>
)

const skyContent = () => (
  <>
    <StarrySky />
    <MainContent />
  </>
)

const HomePage = () => {
  const { colorMode } = useColorMode();
  if (colorMode === 'dark') {
    return skyContent();
  } else {
    return AuroraBackContent();
  }
}

export default function Home() {
  const { siteConfig } = useDocusaurusContext();
  return (
    <Layout
      //@ts-ignore
      title={`${siteConfig.title} Documentation`}
      description="Description will go into a meta tag in <head />"
    >
      <HomePage />
    </Layout >
  );
}
```

But it still doesn't seem to work，Do you have any good suggestions?

**Comment by dulranga** [comment]
https://farm-fe-github-io-lime.vercel.app/
I've done a deployment here
seems like its working

**Comment by dulranga** [comment]
also, there's a rerender issue in the `<MainContent />`
It does re-render whenever the color mode changes which is unnecessary 

I've figured out it's due to the `<AuroraBackground />` component
I'm trying to fix it now

**Comment by ErKeLost** [comment]
rerendering is a deliberate effect that I added, so it might look better, haha

**Comment by ErKeLost** [comment]
> https://farm-fe-github-io-lime.vercel.app/ I've done a deployment here seems like its working

It seems to be working normally. Thanks to your PR, I was working normally at first, and then he started reporting errors under unknown circumstances.

**Comment by dulranga** [comment]
> rerendering is a deliberate effect that I added, so it might look better, haha

Oh didn't know that. I thought it was a bug due to conditional rendering happening in the Component 😄

**Comment by ErKeLost** [comment]
> > rerendering is a deliberate effect that I added, so it might look better, haha
> 
> Oh didn't know that. I thought it was a bug due to conditional rendering happening in the Component 😄

thanks this advice should be taken

**Pull request merged**
