### PR TITLE
fix: avoid vercel & cf pages build error

### PR DESCRIPTION
**Pull request by HsiangNianian**

### CODE REVIEW

**Comment by HsiangNianian** [comment]
@ErKeLost Can you obtain some important information from the deployment error logs of Vercel or Cloudflare Pages? I can't figure out which commit caused the deployment error because I don't have permission to view the deployment logs. Therefore, I can only think of code rollback(https://github.com/farm-fe/farm-fe.github.io/pull/146/commits/cb590df3708520127eb211af9f6c67ddac33acc3)

**Comment by ErKeLost** [comment]
@brightwwu help check it

**Comment by ErKeLost** [comment]
@HsiangNianian hi Documentation is now moved to farm's main repo. https://github.com/farm-fe/farm/tree/v2-dev  If you have any ideas, welcome contribute

**Comment by HsiangNianian** [comment]
Hi Andy, hope everything going well, literally, I'll pull a request if I find something bugs or tiny issues. Thank you for your kind reminder :D
________________________________
发件人: ADNY ***@***.***>
发送时间: 2024年10月20日 12:08
收件人: farm-fe/farm-fe.github.io ***@***.***>
抄送: 简律纯 ***@***.***>; Mention ***@***.***>
主题: Re: [farm-fe/farm-fe.github.io] fix: avoid vercel & cf pages build error (PR #148)


@HsiangNianian<https://github.com/HsiangNianian> hi Documentation is now moved to farm's main repo. https://github.com/farm-fe/farm/tree/v2-dev If you have any ideas, welcome contribute

―

**Pull request closed without merging**
